# Generated by Django 5.0.6 on 2025-10-25 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('Monto fijo', 'Monto fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ciclo_lectivo',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'nivel',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('beca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.beca')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='administracion.ciclolectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_admin', to='administracion_alumnos.estudiante')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.nivel')),
            ],
            options={
                'db_table': 'inscripcion_administrativa',
                'ordering': ['-ciclo__anio', 'nivel', 'subnivel'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=20)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='administracion.inscripcionadministrativa')),
            ],
            options={
                'db_table': 'cuota',
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='MontoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montos_nivel', to='administracion.ciclolectivo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montos_nivel', to='administracion.nivel')),
            ],
            options={
                'db_table': 'monto_nivel',
                'ordering': ['nivel', 'fecha_vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Otro', 'Otro')], max_length=30)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuotas_pagadas', models.ManyToManyField(related_name='pagos', to='administracion.cuota')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Subnivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='administracion.nivel')),
            ],
            options={
                'db_table': 'subnivel',
                'ordering': ['nivel__nombre', 'nombre'],
                'unique_together': {('nivel', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='inscripcionadministrativa',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.subnivel'),
        ),
    ]
