# Generated by Django 5.0.6 on 2025-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='beca',
            table='adm_beca',
        ),
        migrations.AlterModelTable(
            name='ciclolectivo',
            table='adm_ciclo_lectivo',
        ),
        migrations.AlterModelTable(
            name='cuota',
            table='adm_cuota',
        ),
        migrations.AlterModelTable(
            name='inscripcionadministrativa',
            table='adm_inscripcion_administrativa',
        ),
        migrations.AlterModelTable(
            name='montonivel',
            table='adm_monto_nivel',
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='adm_nivel',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='adm_pago',
        ),
        migrations.AlterModelTable(
            name='subnivel',
            table='adm_subnivel',
        ),
    ]
