# Generated by Django 5.0.6 on 2025-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_beca_table_alter_ciclolectivo_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
