# Generated by Django 5.0.6 on 2025-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_beca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolectivo',
            name='anio',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
