# Generated by Django 5.0.6 on 2025-10-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_ciclolectivo_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolectivo',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
    ]
