# Generated by Django 5.0.6 on 2025-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_ciclolectivo_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclolectivo',
            name='activo',
        ),
        migrations.AddField(
            model_name='ciclolectivo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Preparacion', 'En preparación'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ciclolectivo',
            name='anio',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
