# Generated by Django 5.0.6 on 2025-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_remove_ciclolectivo_activo_ciclolectivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolectivo',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
    ]
