# Generated by Django 5.0.6 on 2024-08-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_lectivo', models.IntegerField(unique=True)),
                ('mes_inicio', models.DateField()),
                ('mes_fin', models.DateField()),
                ('porcentaje_interes_mora', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(db_column='cuil_alumno', on_delete=django.db.models.deletion.CASCADE, to='administracion_alumnos.alumno')),
                ('año_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.datosglobales')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fuera_de_termino', models.BooleanField(default=False)),
                ('interes_por_mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.inscripcion')),
            ],
        ),
    ]
