# Generated by Django 5.0.6 on 2024-09-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_lectivo', models.IntegerField(verbose_name='Año Lectivo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de Inscripción')),
                ('monto_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de la Cuota')),
            ],
            options={
                'verbose_name': 'Ciclo Lectivo',
                'verbose_name_plural': 'Ciclos Lectivos',
                'db_table': 'ciclolectivo',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medio_pago', models.CharField(max_length=100, verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medio_pago',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Inscripción')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('descuento_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento por Inscripción')),
                ('debe_inscripcion', models.BooleanField(default=True, verbose_name='Debe Inscripción')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.ciclolectivo', verbose_name='Ciclo Lectivo')),
                ('cuil_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_alumnos.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes de la Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Cuota')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fuera_de_termino', models.BooleanField(default=False, verbose_name='Fuera de Término')),
                ('interes_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interés Aplicado')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a Pagar')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.inscripcion', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuota',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.cuota', verbose_name='Cuota')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
    ]
