# Generated by Django 5.0.6 on 2025-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclolectivo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
