# Generated by Django 5.0.6 on 2025-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_ciclolectivo_activo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vencimientomensual',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='vencimientomensual',
            index=models.Index(fields=['ciclo', 'mes'], name='vencimiento_ciclo_i_7f7522_idx'),
        ),
        migrations.AddConstraint(
            model_name='vencimientomensual',
            constraint=models.UniqueConstraint(fields=('ciclo', 'mes'), name='uniq_vencimiento_por_ciclo_mes'),
        ),
    ]
