# Generated by Django 5.0.6 on 2024-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosglobales',
            name='monto_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
