# Generated by Django 5.0.6 on 2024-12-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_comprobantedrivepago'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comprobantedrivepago',
            table='comprobante_de_pago',
        ),
    ]
