# Generated by Django 5.0.6 on 2024-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_datosglobales_monto_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosglobales',
            name='importe_cuota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
