# Generated by Django 5.0.6 on 2025-04-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0004_remove_comprobantedrivepago_cuil_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='debe_inscripcion',
        ),
    ]
