# Generated by Django 5.0.6 on 2025-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0005_remove_inscripcion_debe_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
