# Generated by Django 5.0.6 on 2025-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0006_alter_inscripcion_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnivelcursado',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Mensual'),
        ),
    ]
