# Generated by Django 5.0.6 on 2025-04-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0007_subnivelcursado_monto_mensual'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comprobantedrivepago',
            table='comprobante_pago',
        ),
    ]
