# Generated by Django 5.0.6 on 2025-04-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0010_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
