# Generated by Django 5.0.6 on 2025-10-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
