# Generated by Django 5.0.6 on 2025-10-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_perfil_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='updated_at',
        ),
    ]
