# Generated by Django 5.0.6 on 2025-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_remove_perfil_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autenticacion/images/usuarios/'),
        ),
    ]
