# Generated by Django 5.0.6 on 2025-11-05 20:45

import apps.autenticacion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autenticacion/images/usuarios/', validators=[apps.autenticacion.validators.validate_image_size_5mb]),
        ),
    ]
