# Generated by Django 5.0.6 on 2025-10-30 19:40

import apps.comprobantes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo remitente (Form)')),
                ('timestamp_form', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora del formulario')),
                ('drive_file_id', models.CharField(max_length=64, unique=True, verbose_name='ID Drive')),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Carpeta Drive')),
                ('drive_mime_type', models.CharField(blank=True, default='', max_length=150, verbose_name='MIME')),
                ('drive_web_view_link', models.URLField(blank=True, default='', verbose_name='Link web')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre original')),
                ('archivo', models.FileField(upload_to=apps.comprobantes.models.ruta_comprobantes, verbose_name='Archivo (local)')),
                ('cuil_estudiante', models.CharField(db_index=True, max_length=11)),
                ('cuil_responsable', models.CharField(db_index=True, max_length=11)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('omitido', 'Omitido'), ('error', 'Error')], default='ok', max_length=20)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='administracion_alumnos.estudiante')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='administracion_alumnos.responsable')),
            ],
            options={
                'db_table': 'documento_comprobante',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
