# Generated by Django 5.0.6 on 2025-10-29 21:14

import apps.comprobantes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo institucional')),
                ('archivo', models.FileField(upload_to=apps.comprobantes.models.ruta_comprobantes, verbose_name='Comprobante adjunto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del comprobante')),
                ('cuil_estudiante', models.CharField(max_length=11, verbose_name='CUIL del estudiante')),
                ('cuil_responsable', models.CharField(max_length=11, verbose_name='CUIL del responsable')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='administracion_alumnos.estudiante', verbose_name='Estudiante')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='administracion_alumnos.responsable', verbose_name='Responsable de pago')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'documento_comprobante',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
