# Generated by Django 5.0.6 on 2025-11-03 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0004_add_estado_documentacion'),
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.DateTimeField()),
                ('correo', models.EmailField(max_length=254)),
                ('url_comprobante', models.URLField(max_length=500)),
                ('cuil_estudiante', models.CharField(max_length=20)),
                ('cuil_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Procesado', 'Procesado')], default='Pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_pago', to='administracion_alumnos.estudiante')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'db_table': 'adm_comprobantes_pago',
                'ordering': ['-marca_temporal'],
            },
        ),
    ]
