# Generated by Django 5.0.6 on 2025-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='fecha_registro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='marca_temporal',
            field=models.CharField(max_length=100),
        ),
    ]
