from django.db import models


class Estudiante(models.Model):
    id = models.AutoField(primary_key=True)
    marca_temporal = models.CharField(max_length=100, blank=True, null=True)
    formulario_email = models.CharField(max_length=255, blank=True, null=True)
    foto = models.CharField(max_length=100, blank=True, null=True)
    salita_grado_ano = models.CharField(max_length=100, blank=True, null=True)
    nivel = models.CharField(max_length=100, blank=True, null=True)
    numero_legajo = models.CharField(max_length=100, blank=True, null=True)
    fecha_recepcion = models.CharField(max_length=100, blank=True, null=True)
    apellidos = models.CharField(max_length=100)
    nombres = models.CharField(max_length=100)
    sexo = models.CharField(max_length=100)
    fecha_nacimiento = models.CharField(max_length=100)
    nacionalidad = models.CharField(max_length=100, blank=True, null=True)
    ciudad = models.CharField(max_length=100, blank=True, null=True)
    calle = models.CharField(max_length=255, blank=True, null=True)
    numero_casa = models.CharField(max_length=100, blank=True, null=True)
    barrio = models.CharField(max_length=100, blank=True, null=True)
    codigo_postal = models.CharField(max_length=100, blank=True, null=True)
    provincia = models.CharField(max_length=100, blank=True, null=True)
    cuil = models.CharField(max_length=100, unique=True)
    dni = models.CharField(max_length=100, unique=True)
    email_alumno = models.CharField(max_length=255, blank=True, null=True)
    religion = models.CharField(max_length=100, blank=True, null=True)
    telefono_fijo = models.CharField(max_length=100, blank=True, null=True)
    telefono_celular = models.CharField(max_length=100, blank=True, null=True)
    telefono_emergencia = models.CharField(max_length=100, blank=True, null=True)
    parentesco = models.CharField(max_length=100, blank=True, null=True)
    peso = models.CharField(max_length=100, blank=True, null=True)
    talla = models.CharField(max_length=100, blank=True, null=True)
    obra_social = models.CharField(max_length=100, blank=True, null=True)
    cual_obra_social = models.CharField(max_length=100, blank=True, null=True)
    problema_neurologico = models.CharField(max_length=100, blank=True, null=True)
    cual_problema_neurologico = models.CharField(max_length=255, blank=True, null=True)
    problema_actividad_fisica = models.CharField(max_length=100, blank=True, null=True)
    certificado_medico = models.CharField(max_length=100, blank=True, null=True)
    problema_aprendizaje = models.CharField(max_length=100, blank=True, null=True)
    cual_problema_aprendizaje = models.CharField(max_length=255, blank=True, null=True)
    atencion_medica = models.CharField(max_length=100, blank=True, null=True)
    alergico = models.CharField(max_length=100, blank=True, null=True)
    dni_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    apellido_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    nombre_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    nacionalidad_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    fecha_nacimiento_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    estado_civil_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    cuil_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    nivel_instruccion_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    calle_responsable1 = models.CharField(max_length=255, blank=True, null=True)
    n_mz_pc_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    barrio_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    ciudad_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    codigo_postal_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    provincia_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    email_responsable1 = models.CharField(max_length=255, blank=True, null=True)
    religion_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    telefono_fijo_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    telefono_celular_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    ocupacion_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    telefono_laboral_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    horario_laboral_responsable1 = models.CharField(max_length=100, blank=True, null=True)
    dni_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    apellido_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    nombre_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    nacionalidad_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    fecha_nacimiento_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    estado_civil_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    cuil_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    nivel_instruccion_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    calle_responsable2 = models.CharField(max_length=255, blank=True, null=True)
    n_mz_pc_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    barrio_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    ciudad_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    codigo_postal_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    provincia_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    email_responsable2 = models.CharField(max_length=255, blank=True, null=True)
    religion_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    telefono_fijo_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    telefono_celular_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    ocupacion_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    telefono_laboral_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    horario_laboral_responsable2 = models.CharField(max_length=100, blank=True, null=True)
    dni_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    apellido_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    nombre_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    nacionalidad_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    fechaNacimiento_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    estadoCivil_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    cuil_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    NivelInstruccion_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    calle_responsableOtro = models.CharField(max_length=255, blank=True, null=True)
    n_mz_pc_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    barrio_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    ciudad_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    codigoPostal_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    provincia_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    email_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    religion_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    telefonoFijo_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    telefonoCelular_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    ocupacion_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    telefonoLaboral_responsableOtro = models.CharField(max_length=100, blank=True, null=True)
    horarioLaboral_ResponsableOtro = models.CharField(max_length=100, blank=True, null=True)
    nivel_ensenanza = models.CharField(max_length=100, blank=True, null=True)
    contrato_fecha = models.CharField(max_length=100, blank=True, null=True)
    contrato_senores1 = models.CharField(max_length=100, blank=True, null=True)
    contrato_dniSenores1 = models.CharField(max_length=100, blank=True, null=True)
    contrato_senores2 = models.CharField(max_length=100, blank=True, null=True)
    contrato_dniSenores2 = models.CharField(max_length=100, blank=True, null=True)
    contrato_domicilioSenores = models.CharField(max_length=255, blank=True, null=True)
    contrato_emailSenores = models.CharField(max_length=100, blank=True, null=True)
    contrato_representacionAlumno = models.CharField(max_length=100, blank=True, null=True)
    contrato_dniAlumno = models.CharField(max_length=100, blank=True, null=True)
    contrato_domicilioAlumno = models.CharField(max_length=255, blank=True, null=True)
    contrato_responsable = models.CharField(max_length=100, blank=True, null=True)
    contrato_dniResponsable = models.CharField(max_length=100, blank=True, null=True)
    contrato_cumplimiento = models.CharField(max_length=255, blank=True, null=True)
    contrato_autorizacionFacturacion = models.CharField(max_length=255, blank=True, null=True)
    imagen_autorizado = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'estudiantes'

    def __str__(self):
        return f"{self.nombres} {self.apellidos} (CUIL: {self.cuil})"