# Generated by Django 5.0.6 on 2025-10-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_estudiante', models.CharField(max_length=100)),
                ('nombres_estudiante', models.CharField(max_length=100)),
                ('sexo_estudiante', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9)),
                ('fecha_nac_estudiante', models.CharField(max_length=100)),
                ('nacionalidad_estudiante', models.CharField(max_length=100)),
                ('religion_estudiante', models.CharField(blank=True, max_length=100, null=True)),
                ('cuil_estudiante', models.CharField(max_length=50)),
                ('dni_estudiante', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_documentacion', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'estado_documentacion',
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.CharField(max_length=100)),
                ('ciudad_a_los_dias', models.CharField(max_length=100)),
                ('senores1', models.CharField(max_length=100)),
                ('dni_senores1', models.CharField(max_length=50)),
                ('senores2', models.CharField(max_length=100)),
                ('dni_senores2', models.CharField(max_length=50)),
                ('domicilios_senores', models.CharField(max_length=150)),
                ('domicilio_especial_electronico', models.CharField(max_length=150)),
                ('actuan_nombres_estudiante', models.CharField(max_length=100)),
                ('dni_acutan_estudiante', models.CharField(max_length=50)),
                ('domicilio_actuan_estudiante', models.CharField(max_length=150)),
                ('responsable_pago', models.CharField(max_length=100)),
                ('dni_responsable_pago', models.CharField(max_length=50)),
                ('manifiesta_responsable', models.CharField(max_length=200)),
                ('autoriza_facturacion_a', models.CharField(max_length=200)),
                ('autoriza_imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'documentacion',
            },
        ),
        migrations.CreateModel(
            name='ContactoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_estudiante', models.CharField(max_length=100)),
                ('provincia_estudiante', models.CharField(max_length=100)),
                ('barrio_estudiante', models.CharField(max_length=100)),
                ('calle_estudiante', models.CharField(max_length=100)),
                ('n_mz_pc_estudiante', models.CharField(max_length=100)),
                ('codigo_postal_estudiante', models.CharField(max_length=10)),
                ('email_estudiante', models.CharField(max_length=100)),
                ('tel_fijo_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_cel_estudiante', models.CharField(max_length=50)),
                ('tel_emergencia_estudiante', models.CharField(max_length=50)),
                ('parentesco_estudiante', models.CharField(max_length=100)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'contacto_estudiante',
            },
        ),
        migrations.CreateModel(
            name='InformacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_cursado', models.CharField(max_length=100)),
                ('donde_cursado', models.CharField(max_length=100)),
                ('asignaturas_pendientes', models.CharField(max_length=100)),
                ('indica_asig_pendientes', models.CharField(max_length=200)),
                ('tiene_hermanos_institucion', models.CharField(max_length=50)),
                ('cuantos_hermanos', models.CharField(blank=True, max_length=10, null=True)),
                ('como_conociste_institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('eligio_institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_academica', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'info_academica',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.CharField(max_length=100)),
                ('email_registro', models.CharField(max_length=100)),
                ('foto_estudiante', models.CharField(blank=True, max_length=200, null=True)),
                ('num_legajo_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.CharField(blank=True, max_length=100, null=True)),
                ('salita_grado_anio_estudiante', models.CharField(max_length=100)),
                ('nivel_estudiante', models.CharField(max_length=100)),
                ('curso_anio_estudiante', models.CharField(max_length=100)),
                ('turno_estudiante', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=20)),
                ('nivel_ensenanza', models.CharField(max_length=100)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nac', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('cuil', models.CharField(max_length=50)),
                ('nivel_instruccion', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('n_mz_pc', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_cel', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=100)),
                ('tel_laboral', models.CharField(max_length=50)),
                ('horario_trabajo', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'responsable',
            },
        ),
        migrations.CreateModel(
            name='SaludEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_estudiante', models.CharField(max_length=20)),
                ('talla_estudiante', models.CharField(max_length=20)),
                ('obra_social_estudiante', models.CharField(max_length=100)),
                ('cual_osocial_estudiante', models.CharField(max_length=100)),
                ('problema_neurologico_estudiante', models.CharField(max_length=100)),
                ('cual_prob_neurologico_estudiante', models.CharField(max_length=100)),
                ('problema_fisico_estudiante', models.CharField(max_length=100)),
                ('certificado_medico_estudiante', models.CharField(max_length=100)),
                ('problema_aprendizaje_estudiante', models.CharField(max_length=100)),
                ('cual_aprendizaje_estudiante', models.CharField(max_length=100)),
                ('atencion_medica_estudiante', models.CharField(max_length=100)),
                ('alergia_estudiante', models.CharField(blank=True, max_length=200, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='administracion_alumnos.estudiante')),
            ],
            options={
                'db_table': 'salud_estudiante',
            },
        ),
    ]
