# Generated by Django 5.0.6 on 2025-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0002_alter_saludestudiante_certificado_medico_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='horario_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='tel_laboral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
