# Generated by Django 5.0.6 on 2025-10-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0003_alter_responsable_horario_trabajo_and_more'),
    ]

    operations = [
    ]
