# Generated by Django 5.0.6 on 2025-11-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0003_alter_responsable_horario_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(
                    max_length=20,
                    choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado')],
                    default='Pendiente'
                )),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='estado_documentacion',
                    to='administracion_alumnos.estudiante'
                )),
            ],
            options={
                'db_table': 'estado_documentacion',
            },
        ),
    ]
