# Generated by Django 5.0.6 on 2025-11-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0004_add_estado_documentacion'),
        ('administracion_alumnos', '0004_auto_20251031_2014'),
    ]

    operations = [
    ]
